'use client';
import { ThemeProvider } from '@/components/ThemeProvider';
import Container from '@/components/ui/container';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[#0a192f]`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<Container>{children}</Container>
				</ThemeProvider>
			</body>
		</html>
	);
}
